services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - "MY_NAME=Student"

  database:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - ./data:/var/lib/postgresql/data