"""add order total

Revision ID: c08fc6157014
Revises: 4da003b7ee78
Create Date: 2026-06-30 16:02:49.964862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08fc6157014'
down_revision: Union[str, Sequence[str], None] = '4da003b7ee78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('orders', sa.Column('total', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total')
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
