# Generated by Django 6.0.3 on 2026-03-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='original_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='screen_digonal',
            new_name='screen_diagonal',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specs',
            new_name='specifications',
        ),
    ]
