# Generated by Django 6.0.3 on 2026-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rename_images_product_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
