# Generated by Django 6.0.3 on 2026-03-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_product_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.CharField(null=True),
        ),
    ]
