# Generated by Django 6.0.3 on 2026-03-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_product_reviews_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_url',
            new_name='images_url',
        ),
    ]
