# Generated by Django 6.0.3 on 2026-03-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_rename_img_url_product_images_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images_url',
            new_name='images',
        ),
    ]
