# Generated by Django 6.0.3 on 2026-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_rename_images_url_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
