# Generated by Django 6.0.3 on 2026-03-27 15:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('memory', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('promo_price', models.CharField(max_length=50, null=True)),
                ('original_price', models.CharField(max_length=50, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), blank=True, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, null=True)),
                ('reviews_count', models.CharField(null=True)),
                ('screen_diagonal', models.CharField(max_length=50, null=True)),
                ('screen_resolution', models.CharField(max_length=50, null=True)),
                ('product_code', models.CharField(max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True, unique=True)),
                ('status', models.CharField(default='New', max_length=50, null=True)),
            ],
        ),
    ]
